server:
  port: 8082

spring:
  application:
    name: shopping-redis
  profiles:
    active: name



eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    hostname: shopping-redis
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8888/eureka
