spring:
  application:
    name: gateway
  profiles:
    active: dev

server:
  port: 8008

zuul:
  sensitiveHeaders: x-access-token,token
  routes:
    api-redis:
      path: /api/redis/**
      serviceId: shopping-redis
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

eureka:
  instance:
    hostname: shopping-gateway
    # 实例使用ip进行访问
    prefer-ip-address: true
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8888/eureka/

