server:
  port: 8888
spring:
  application:
    name: eureka
  profiles:
    active: dev

security:
  basic:
    enabled: true
  user:
    name: admin
    password: 123456

eureka:
  server:
    # 关闭保护机制，确保注册中心可以将不可用的实例正确删除
    enable-self-preservation: true
    # 清理无效节点间隔时间 默认 60*1000
    eviction-interval-timer-in-ms: 5000
  instance:
    preferIpAddress: false
    hostname: shopping-eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:8888/eureka/
